### ISSUE TITLE
Pino Json Colorizer

### ISSUE THREAD

**Issue by dancastillo** [pinojs/json-colorizer#2]
### Description

I realize this isn't the correct repository but I am unable to create an issue in [@pinojs/json-colorizer](https://github.com/pinojs/json-colorizer).

It looks like the readme is not updated for referencing the correct [npm package](https://www.npmjs.com/package/@pinojs/json-colorizer), there is an open [pull request](https://github.com/pinojs/json-colorizer#installation) for a fix.

### Current Behavior
Directions in the [readme](https://github.com/pinojs/json-colorizer/blob/master/README.md)
```
npm install json-colorizer
```

### Expected Behavior
Directions in [readme](https://github.com/pinojs/json-colorizer/blob/master/README.md)
```
npm install @pinojs/json-colorizer
```

**Comment by jsumners** [comment]
Closed by #1
