### ISSUE TITLE
Updating for v9

### ISSUE THREAD

**Issue by Ranieri93** [pinojs/json-colorizer#3]
👋 I'm Ranieri, I stumbled upon [issue #1762](https://github.com/pinojs/pino/issues/1762), and I figured that I could help!

Could you provide me some additional informations? 
Like what is a suitable number of commits to measure interest? Do you have in mind a range of dates to inspect data coming from [npm-stat.com](https://npm-stat.com/)?
Regarding the second point I never worked with CI configs or with `Tap` testing suite, but I can learn!

I'm also totally new to Open Source in general, so I hope you'll excuse me if I don't know some procedures or steps, but I'll help as much as I can!

@jsumners

**Comment by jsumners** [comment]
> Do you have in mind a range of dates to inspect data coming from [npm-stat.com](https://npm-stat.com/)?

The default is one year to date, and I think that is sufficient. This package shows very limited usage -- https://npm-stat.com/charts.html?package=%40pinojs%2Fjson-colorizer&from=2022-08-27&to=2023-08-27

I also don't see any of the Pino packages depending on this one -- https://www.npmjs.com/package/@pinojs/json-colorizer?activeTab=dependents

From the commit history, it looks like @capaj created this fork and contributed it to the org. I'd like to hear if they remember the reasoning, and if they think it should continue to exist.

I'd also like to hear @mcollina's opinion.

My opinion is that this should be decommissioned (archived in GitHub) and marked as deprecated on npm.

**Comment by jsumners** [comment]
> I am not sure what you are talking about here. Can you specify?

As shown above, it is not currently used by any Pino project. Given the lack of maintenance of this package, and the lack of usage in other org projects, I think we are better off reducing our burden.

**Comment by capaj** [comment]
Oh right. Feel free to transfer the package back to me or archive it.
I find it useful and I use it for logging on my development machine on projects I work on daily basis. I would most likely find time to add esm modules and update dependencies.

**Comment by Ranieri93** [comment]
@jsumners and @capaj  thank you so much! Then we'll consider this as deprecated and I'll move to the next one

**Comment by jsumners** [comment]
@Ranieri93 we haven't heard @mcollina's opinion yet.

**Comment by Ranieri93** [comment]
Oh, you're entirely correct! Let's hear @mcollina!

**Comment by mcollina** [comment]
It would be great if we could have colorized output of JavaScript objects in pino-pretty. However a PR to do that never materialized. I think we should ideally do that instead of archiving/transfering.

**Comment by jsumners** [comment]
Okay, I have created the `next` branch https://github.com/pinojs/json-colorizer/tree/next

**Comment by Ranieri93** [comment]
Hey @jsumners, I would like to start working on this. 
Now I'll pose some questions, presumably even stupid ones. It's my first time so I'm gonna ask you for some patience. 😄 

- Updating dependencies: I assume try to update every package to the latest version and see if tests are still up and running. Do I need anything else?
- Dropping Node <= 16: Here unfortunately I'm in the dark, could you elaborate a little bit? 
- Updating CI configuration: I see that here we use [Travis](https://www.travis-ci.com/) and that the config file is pretty straight, so I guess won't be hard. Do I need to pay attention to something in particular?
- Testing suite configuration (tap): Can you elaborate as well? Should I migrate the current framework to tap? 
- Anything else you think is required to achieve this is welcome.

Thank you so much in advance!

**Comment by jsumners** [comment]
> * Updating dependencies: I assume try to update every package to the latest version and see if tests are still up and running. Do I need anything else?

No, that should be all. The only catch is to make sure we can actually use the latest versions. Some dependencies have shifted to ESM only, and that won't work. Such dependencies would need to be pinned to the latest version that is non-ESM.

> * Dropping Node <= 16: Here unfortunately I'm in the dark, could you elaborate a little bit?

This means removing the CI configuration for any version of Node less than 18. It can also mean going through the code and removing/updating any blocks that specifically tagged as something like "for Node X support".

> * Updating CI configuration: I see that here we use [Travis](https://www.travis-ci.com/) and that the config file is pretty straight, so I guess won't be hard. Do I need to pay attention to something in particular?

I would remove Travis and migrate it to GitHub Actions.

> * Testing suite configuration (tap): Can you elaborate as well? Should I migrate the current framework to tap?

That would be nice in order to keep thing consistent across the org. But it is definitely not a hard requirement.

**Comment by Ranieri93** [comment]
Should we consider this as done?

**Comment by jsumners** [comment]
Thank you @Ranieri93.
